version: "3"

services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://docker-mysql:3306/app
    depends_on:
      - docker-mysql

  docker-mysql:
    image: mysql:5.7
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/1-dump.sql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: app
      MYSQL_USER: peter
      MYSQL_PASSWORD: strongpassword
    ports:
      - "3306:3306"
      
volumes:
  mysql: